name: aidbox-python-sdk-example
services:
  aidbox-db:
    image: "healthsamurai/aidboxdb:16.1"
    env_file:
      - ./env/db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  aidbox:
    build: ./aidbox-project
    depends_on:
      build-seeds:
        condition: service_completed_successfully
      aidbox-db:
        condition: service_healthy
    ports:
      - 8080:8080
    env_file:
      - ./env/aidbox
    environment:
      - AIDBOX_LICENSE
    volumes:
      - ./aidbox-project/zenproject:/aidbox-project
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 30s
      retries: 50
  build-seeds:
    image: bedasoftware/fhirsnake:latest
    command:
      - export
      - --output
      - /app/zenproject/seeds.ndjson.gz
    volumes:
      - ./aidbox-project/zenproject:/app/zenproject
      - ./aidbox-project/resources/seeds:/app/resources
  backend:
    build:
      context: ./backend
    depends_on:
      aidbox:
        condition: service_healthy
    env_file:
      - ./env/backend
    volumes:
      - ./backend:/app
    command:
      [
        "poetry",
        "run",
        "gunicorn",
        "main:create_gunicorn_app",
        "--reload",
        "--worker-class",
        "aiohttp.worker.GunicornWebWorker",
        "-b",
        "0.0.0.0:8081",
      ]

