version: '3.1'
services:
  backend:
    build: .
    command: ["pipenv", "run", "gunicorn", "main:create_app", "--worker-class", "aiohttp.worker.GunicornWebWorker", "-b", "0.0.0.0:8081", "--reload"]
    depends_on:
      - devbox
    links:
      - devbox
    env_file:
      - .env
    volumes:
      - ./:/app:cached
      - ./config:/var/config:cached
    # Colored logs
    tty: true
  devbox:
    image: "healthsamurai/devbox:stable"
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./config:/var/config:cached
  devbox-db:
    image: "healthsamurai/aidboxdb:13.2"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
