[tool.black]
line-length = 100
target-version = ['py38']
exclude = '''
(
  /(
    | \.git
    | \.pytest_cache
    | htmlcov
    | locales
    | resources
    | requirements
    | embed
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
line_length = 100
default_section = "THIRDPARTY"
known_first_party = ["app"]

[tool.autohooks]
mode = "pythonpath"
pre-commit = ["autohooks.plugins.black", "autohooks.plugins.isort"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --color=yes --junitxml=report.xml --cov-report html --cov-report term:skip-covered --doctest-modules"
testpaths = ["tests"]
log_cli = true
log_cli_level = "INFO"
norecursedirs = "embed"