version: '3.1'
services:
  aidbox-db:
    image: "healthsamurai/aidboxdb:14.9"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       aidbox
  aidbox:
    image: "healthsamurai/aidboxone:stable"
    depends_on:
      - aidbox-db
    links:
      - "aidbox-db:database"
    ports:
      - "8080:8080"
    env_file:
    - env_tests
    environment:
      PGHOST: database
      PGDATABASE: aidbox
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      AIDBOX_CONFIG: /var/config/config.edn
      AIDBOX_LICENSE: ${AIDBOX_LICENSE}
    volumes:
      - ./zenproject:/zenproject
  aidbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - aidbox
    depends_on:
      - aidbox
    healthcheck:
      test: curl --fail http://aidbox:8080/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  app:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON:-3.11}
    command: ["pipenv", "run", "pytest"]
    depends_on:
      aidbox-healthcheck:
        condition:
          service_healthy
    links:
     - aidbox
    env_file:
     - env_tests
    ports:
     - "8081:8081"
    volumes:
     - .:/app
