build-test:
	docker compose -f compose.test-env.yaml build

stop-test:
	docker compose -f compose.test-env.yaml stop

down-test:
	docker compose -f compose.test-env.yaml down

run-test:
	./run_test.sh

